### ISSUE TITLE
FuckBattleEye critical error

### ISSUE THREAD

**Issue by Baronneke** [G-E-N-E-S-I-S/FuckBattlEye#2]
System.IndexOutOfRangeException: 'The index is outside the matrixborder.'

Error occures right after:
-------------------------------------
Namespace FuckBattlEye
{
    static unsafe class FuckBattlEye
    {
        public static void Run(string szCheatPath, string szProcessName)
        {
            Process.EnterDebugMode(); // GET SeDebugPrivilege
            Process procTarget = Process.GetProcessesByName(szProcessName)[0];

            var HandleList = EnumHandles(procTarget.Id, 0x10/*VM_READ*/ & 0x20/*VM_WRITE*/); /*0x1fffff FULL_CONTROL*/

            if (HandleList.Count > 0)
            {
                foreach (var HandleInformation in HandleList)
                {
                    Process procService = Process.GetProcessById(HandleInformation.Id);

                    Console.WriteLine($"{procService.ProcessName} - {HandleInformation.hProcess.ToString("x2")}");
                    
                    if (ElevateHandle(procService.Handle, HandleInformation.hProcess, true, true))
                    {
                        IntPtr hProcess = StartProcessAsUser(null, $"{szCheatPath} {HandleInformation.hProcess}", null, true, procService.Handle);
                        ElevateHandle(procService.Handle, HandleInformation.hProcess, false, false);
                        break;
                    }
                }
            }
        }

**Comment by Br3n0k** [comment]
same problem
