### ISSUE TITLE
How to this works on 64bit OS?

### ISSUE THREAD

**Issue by kani-jp** [G-E-N-E-S-I-S/FuckBattlEye#4]
Dear,

I try Compile and Run, output "Unknown NT_STATUS: 5f6ee60c0000004".

Debug, FuckBattleEye.cs Line127 EnumHandles.

1time
Before : pinfo = 0, nBufferLength = 0
After : pinfo = 0, nBufferLength = **20**, ntstatus = 0xC0000004.

2time
Before : pinfo = **16344256**, nBufferLength = **20**,
After : pinfo = **16344256**, nBufferLength = **1130596**, ntstatus = **0x5f6ee60c0000004**.

```
while (ntstatus != 0/*NT_SUCCESS*/)
{
    ntstatus = Win32.NtQuerySystemInformation(0x10/*HANDLE INFORMATION*/, pInfo, nBufferLength, ref nBufferLength);
                
    if (ntstatus == 0xC0000004/*STATUS_INFO_LENGTH_MISMATCH*/)
    {
        if (pInfo != IntPtr.Zero)
            Marshal.FreeHGlobal(pInfo);

        pInfo = Marshal.AllocHGlobal(nBufferLength);
    }
    else if (ntstatus != 0) // DON'T ALERT ON NT_SUCCESS :)
    {
        Console.WriteLine($"Unknown NT_STATUS: {ntstatus.ToString("x2")}");
        Console.ReadLine();
        Environment.Exit(0);
    }
}
```

Why 2nd time retuened "ntstatus" too long?
I infer "Win32.NtQuerySystemInformation" works only 32bit, but run 32bit mode (on 64bit OS) failed as same.
Please teach me hint of how to change.

Regards,

**Comment by kani-jp** [comment]
Enviroments
Windows 10 Home 64Bit
OS build 15063.413
Microsoft Visual C# 2015
.Net Framework 4.5, 4.5.1, 4.5.2, 4.6, 4.6.1

Regards,

**Comment by masterben2432** [comment]
Same problem here
